from .user_repository import UserRepository
from .file_repository import FileRepository
from .permission_repository import PermissionRepository
from .role_repository import RoleRepository
from .vacancy_repository import VacancyRepository
from .candidate_repository import CandidateRepository